### ISSUE TITLE
Использовать Storybook для превью компонентов.

### ISSUE THREAD

**Issue by ghost** [itgenio/uikit#49]
Storybook удобен, и его легко внедрить

**Comment by afrokick** [comment]
Мы используем на другом проекте сторибук, но пока не понятно, в чем преимущество по сравнению с текущий приложением.

Кол-во кода чтобы сделать пример - такое же.
Пока преимущество только в том, что автоматически составляется меню(хотя это не сложно допилить).

**Comment by vector1old** [comment]
В StoryBook вроде можно сразу встраивать макеты из Figma, и да, менюшка автоматом состовляется с типами.
